### ISSUE TITLE
FDM Add on not working on chrome unstable(dev version on ubuntu)

### ISSUE THREAD

**Issue by 0nahid** [FreeDownloadManagerTeam/fdm-addons-docs#2]
I've downloaded the add on from web store but it's not grabbing download links....

**Comment by shahoob** [comment]
> I've downloaded the add on from web store but it's not grabbing download links....

I'm sorry for the late reply but this repository is for how to make add-ons for Free Download Manager, not for FDM's browser extensions.

You can use [the forum](https://www.freedownloadmanager.org/board/viewforum.php?f=1) instead.
