### ISSUE TITLE
fdm://

### ISSUE THREAD

**Issue by V70024** [FreeDownloadManagerTeam/fdm-addons-docs#5]
I wanted to redirect a file link to my download manager program, FDM, through a JavaScript code on an HTML page. However, the process is not working properly.

To test the code, please run the HTML page on a mobile phone and make sure FDM is installed on your phone.

If FDM does not have this capability, I would be happy if this feature could be added to the program in the new version, so that all developers can take full advantage of this excellent feature with its documentation.

### HTML page:
``` html
<!DOCTYPE html>
<html>

      <head>
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Download with FDM</title>
      </head>

      <body>
            <input type="text" class="shadow form-control rounded-4" id="inputLink"
                  value="https://blog.loadero.com/wp-content/uploads/2020/07/Upload-770x515.jpg" readonly>
            <button id="download-fdm">Download</button>
      </body>

      <script>

            function downloadWithFDM() {
                  const imageUrl = document.getElementById("inputLink").value;
                  if (imageUrl && window.confirm('Download with FDM?')) {
                        window.open("fdm://download?url=" + encodeURIComponent(imageUrl));
                  }
            }
            const downloadFdmButton = document.getElementById('download-fdm');

            downloadFdmButton.addEventListener("click", downloadWithFDM);
      </script>

</html>
```

**Comment by hlf20010508** [comment]
Hi, did you figure it out?
`fdm:` does raise the client, but `fdm:` is also included in the url, which makes it unusable.
`fdm://download?url=http://test.com` results in
![image](https://github.com/user-attachments/assets/444fac4b-21fa-4869-b613-cf345022fdba)
Any idea?

**Comment by hlf20010508** [comment]
The FDM Support Team gave me an example in java.
```java
String sUrl = new String("https://dn3.freedownloadmanager.org/6/latest/fdm_x64_setup.exe");

JSONObject json = new JSONObject();
try {
    json.put("url", sUrl);
}catch(JSONException e) {
    e.printStackTrace();
}

String s = new String();
s = "fdm://download/?";
s += Uri.encode(json.toString()); 
```
The string behind `?` is a encoded json string.

If not encoded, It looks like
```
fdm://download/?{"url": "https://dn3.freedownloadmanager.org/6/latest/fdm_x64_setup.exe"}
```

After encoding, it would be
```
fdm://download/?%7B%22url%22%3A%22https%3A%2F%2Fdn3.freedownloadmanager.org%2F6%2Flatest%2Ffdm_x64_setup.exe%22%7D
```
